stages:
  - test
  - deploy

services:
    - postgres:9.3

variables:
  POSTGRES_DB: dfqidqn21ah4e6
  POSTGRES_USER: plrcxuvelqmsmc
  POSTGRES_PASSWORD: 2d073380ee022a7db5d926a417f6a4589047ae33d81f38cbdc65a1c8a9f04b1e

test:
  stage: test
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  #- export DATABASE_URL=postgres://postgres:@postgres:5432/project_walkietechie_app
  - export DATABASE_URL=postgres://plrcxuvelqmsmc:2d073380ee022a7db5d926a417f6a4589047ae33d81f38cbdc65a1c8a9f04b1e@ec2-54-235-104-136.compute-1.amazonaws.com:5432/dfqidqn21ah4e6
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  #- add-apt-repository ppa:deadsnakes/ppa no need of this
  - apt-get update
  - apt-get install python3
  - pip install -r requirements.txt
  - python ./manage.py test

staging:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=walkietechie-photo-app --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

production:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=walkietechie-photo-app --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags