stages:
  - test
  - deploy

services:
    - postgres:9.3

variables:
  POSTGRES_DB: project_walkietechie_app
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

test:
  stage: test
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - export DATABASE_URL=postgres://postgres:@postgres:5432/project_walkietechie_app
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  #- add-apt-repository ppa:deadsnakes/ppa no need of this
  - apt-get update
  - apt-get install python3
  - pip install -r requirements.txt
  - python ./manage.py test

staging:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=walkietechie-photo-app --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

production:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=walkietechie-photo-app --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags